apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:9BoT63JRWIGIuMhOk12b3Cp0QA6GJcdW4eIyv6QaZqiO+Q90A63RIv1pzghhSaPxjhBGTFU7XcA1M2u2eECmfMZNdhPJHi+0BEaCG7b8a5A+FttmWyp2z6SfhRkUBgiNRpNdZUa616xhYLuND0QeLuYIrTAxsQy+eh71ogg47XDd1nzEnHzRLMDWJ/sLSs3vJGX6uiUUYmHo8muttai1q5u5DPmUzm/C7fj+T3HLp0C8s0e551VTVgR2DXs2vAHU,iv:LN9CrrU9lwcin7zQ0aBpmFAGGkaGs7MVKnBuQH6RVrk=,tag:4nZkhFHMbL5DtVndVbAbyA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: registry-secret
    namespace: react-tutorial
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18ej2rxffusws47jzk4nq0lc7tw9hqd80lnazh2yg5m6utle4jg9qvpa7fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVVRneHFibWFxZS9oUkEy
            cTh4WHhsVHJoSDJuVmt6YVV6aW5mb25kcFVjClFyNFhDTklJbExySDg5YmRtbjlZ
            RDJoMU1PMDd4MUNUblJ6TVFIMHRGN1EKLS0tIHZOMXRabEZWSWVobTFHU2kzSHpH
            ajlaZVhXLzRFOG1iMSs2cldGN2tXOEEKGXAjZ9tjQjiiWIxAGEi9UKWy3IjsfAZJ
            gaJD7gHnhO3ByuhQLZDdbusIqyAnN25fEchziRmUIMDtIj93W4KHIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-19T16:23:37Z"
    mac: ENC[AES256_GCM,data:WkVdFl7zQMptzDYkAtYt0U4q4/+gtHPbQ+cgimKU0pH/yoEQWH0XCOSLbCMkIHI2upDvoYTYp3rrpm4Dhh0JCY56AbBddEjgAsJjMvrWAxp3YyozmJaAU/tksV0ROO9jI3t2o6O8UNunqCv3G3R8AAOpfHZiRbQm2suJv2Uo5ss=,iv:U2luAqbPTiJvDWWPur0GQn8pd22Dtru/1vGY1ZULoh0=,tag:wjsvrA/NDDOyKkqGLU9dSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3

